version: '3.8'

services:
  web:
    container_name: jasperreports
    image: bitnami/jasperreports:latest
    restart: always  
    depends_on:
      - db
    ports:
      - "9091:8080"
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    environment:
      - JASPERREPORTS_USERNAME=${JASPER_USER}
      - JASPERREPORTS_PASSWORD=${JASPER_PASSWORD}
      - JASPERREPORTS_DATABASE_HOST=mariadb
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=${DB_USER}
      - JASPERREPORTS_DATABASE_PASSWORD=${DB_PASSWORD}
      - JASPERREPORTS_DATABASE_NAME=${DB_NAME}
    networks:
      - default
      - oracle-adb-network

  db:
    container_name: mariadb
    image: bitnami/mariadb:latest
    restart: always  
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - default

networks:
  oracle-adb-network:
    external: true

volumes:
  mariadb_data:
  jasperreports_data: